package co.id.yokke.multiacquiring.common.constant;

public class CommonMessage {

    public static String SHORT_CODE_SUCCESS = "SUCCESS";
    public static String SHORT_CODE_FAIL_NULL_ERROR = "NULL_ERROR";
    public static String SHORT_CODE_FAIL_DATA_NOT_EXIST = "DATA_NOT_EXIST";
    public static String SHORT_CODE_FAIL_DATA_ALREADY_EXIST = "DATA_ALREADY_EXIST";
    public static String SHORT_CODE_TIME_OUT = "TIMEOUT";
    public static String SHORT_CODE_EXPIRE = "TOKEN_EXPIRE";
    public static String SHORT_CODE_TOKEN_INVALID = "TOKEN_INVALID";
    public static String SHORT_CODE_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static String SHORT_CODE_INSUFFICIENT_PRIVILEGES="INSUFFICIENT_PRIVILEGES";
    public static String SHORT_CODE_BETWEEN_DATE_60_DAYS = "SHORT_CODE_BETWEEN_DATE_60_DAYS";
    public static String SHORT_CODE_BIG_DATA = "SHORT_CODE_BIG_DATA";
    public static String SHORT_CODE_SQL_ERROR = "SHORT_CODE_SQL_ERROR";
    
    public static String SHORT_CODE_INVALID_FORMAT_EXCEPTION = "INVALID_FORMAT_EXCEPTION";
    public static String SHORT_CODE_INVALID_FILE_EXCEPTION = "INVALID_FILE_EXCEPTION";
    public static String SHORT_CODE_INVALID_HEADER_EXCEPTION = "INVALID_HEADER_EXCEPTION";
    
    public static String SHORT_CODE_FAIL_BAD_REQUEST= "BAD_REQUEST";
    public static String SHORT_CODE_FAIL_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static String SHORT_CODE_FAIL_NMID_NOT_SAME = "NMID_NOT_SAME";
    public static String SHORT_CODE_FAIL_MERCHANT_NAME_NOT_SAME = "MERCHANT_NAME_NOT_SAME";
    public static String SHORT_CODE_INVALID_EMPTY_UPLOAD_TID = "INVALID_EMPTY_UPLOAD_TID";
    public static String SHORT_CODE_INVALID_SAME_NMID_REQUEST = "INVALID_SAME_NMID_REQUEST";
    public static String SHORT_CODE_INVALID_INVALID_EMPTY_MCC_QRIS = "INVALID_EMPTY_MCC_QRIS";
    public static String SHORT_CODE_INVALID_INVALID_INPUT_MUST_NUMBER = "INVALID_INPUT_MUST_NUMBER";
    public static String SHORT_CODE_INVALID_RAC_CONFIG_EXCEPTION = "INVALID_RAC_CONFIG_EXCEPTION";
    public static String SHORT_CODE_INVALID_TID_MORE_8_CHAR_EXCEPTION = "INVALID_TID_MORE_8_CHAR_EXCEPTION";
    public static String SHORT_CODE_FAIL_QR_GENERATE = "FAILED_GENERATE_QR";
}
